name: Rust Unit Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: 1.94
          profile: minimal
          override: true

      - name: Test
        run: cargo test
